# Generated by Django 5.1.4 on 2026-01-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_desc', models.CharField(max_length=1000)),
                ('item_price', models.IntegerField()),
                ('item_image', models.CharField(default='https://imgs.search.brave.com/ly6q72bVHFGys1gJtrLNOkcfdZdZbZuIpJg36gF3bdA/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly91cy4x/MjNyZi5jb20vNDUw/d20veXVwaXJhbW9z/L3l1cGlyYW1vczE0/MDcveXVwaXJhbW9z/MTQwNzAyNDE0LzMw/MjE4ODMzLWZvb2Qt/ZGVzaWduLW92ZXIt/YmVpZ2UtYmFja2dy/b3VuZC12ZWN0b3It/aWxsdXN0cmF0aW9u/LmpwZz92ZXI9Ng', max_length=500)),
            ],
        ),
    ]
