# Generated by Django 5.1.4 on 2026-01-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://imgs.search.brave.com/ly6q72bVHFGys1gJtrLNOkcfdZdZbZuIpJg36gF3bdA/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly91cy4x/MjNyZi5jb20vNDUw/d20veXVwaXJhbW9z/L3l1cGlyYW1vczE0/MDcveXVwaXJhbW9z/MTQwNzAyNDE0LzMw/MjE4ODMzLWZvb2Qt/ZGVzaWduLW92ZXIt/YmVpZ2UtYmFja2dy/b3VuZC12ZWN0b3It/aWxsdXN0cmF0aW9u/LmpwZz92ZXI9Ng', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_desc',
            field=models.CharField(max_length=1000),
        ),
    ]
